# Generated by Django 4.1.5 on 2023-09-20 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_post_text_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=15)),
                ('image_url', models.URLField(max_length=400)),
                ('title', models.CharField(max_length=100)),
                ('title_size', models.CharField(max_length=10)),
                ('title_weight', models.CharField(max_length=10)),
                ('FK_post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_thumbnail', to='portfolio.post')),
            ],
        ),
    ]
