# Generated by Django 4.1.5 on 2023-09-27 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_thumbnail_borderradius'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thumbnail',
            name='title_size',
        ),
    ]
