# Generated by Django 4.1.6 on 2023-02-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listings_comments_bids'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='min_bid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
