# Generated by Django 4.1.6 on 2023-02-14 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listings_min_bid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listings',
            old_name='min_bid',
            new_name='minBid',
        ),
        migrations.AlterField(
            model_name='bids',
            name='FK_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_bids', to='auctions.listings'),
        ),
        migrations.AlterField(
            model_name='bids',
            name='FK_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_bids', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comments',
            name='FK_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_comments', to='auctions.listings'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='FK_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FK_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_watchList', to='auctions.listings')),
                ('FK_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_watchlist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
