# Generated by Django 4.1.6 on 2023-02-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_rename_min_bid_listings_minbid_alter_bids_fk_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='bidsUntilNow',
            field=models.IntegerField(default=0),
        ),
    ]
