# Generated by Django 4.1.5 on 2023-02-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_listings_bidsuntilnow'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='winner_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
