# Generated by Django 4.1.5 on 2023-02-15 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_listings_winner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='is_close',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.CharField(max_length=240),
        ),
    ]
