# Generated by Django 4.1.5 on 2023-06-16 17:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_posts_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='timestamp',
            field=models.DateField(default=datetime.datetime(2023, 6, 16, 17, 1, 5, 212693)),
        ),
    ]
