# Generated by Django 4.1.5 on 2023-06-20 08:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_remove_user_is_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='FK_likes_from_users',
        ),
        migrations.AddField(
            model_name='posts',
            name='likes_from_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='likes_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
