# Generated by Django 4.1.5 on 2023-07-04 07:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_remove_posts_fk_likes_from_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='likes_from_users',
            field=models.ManyToManyField(blank=True, related_name='likes_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
