# Generated by Django 4.1.5 on 2023-07-07 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0013_alter_follow_fk_followers_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='FK_followers_users',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='followers_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='follow',
            name='FK_following_users',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='following_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
