# Generated by Django 4.1.5 on 2023-07-07 08:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0024_alter_user_fk_followers_users_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='FK_followers_users',
        ),
        migrations.RemoveField(
            model_name='user',
            name='FK_following_users',
        ),
        migrations.AddField(
            model_name='user',
            name='FK_followers_users',
            field=models.ManyToManyField(blank=True, related_name='followers_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='FK_following_users',
            field=models.ManyToManyField(blank=True, related_name='following_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
