# Generated by Django 4.1.5 on 2023-07-07 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0025_remove_user_fk_followers_users_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='FK_followers_users',
        ),
        migrations.RemoveField(
            model_name='user',
            name='FK_following_users',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follows', models.ManyToManyField(blank=True, related_name='user_following', to='network.profile')),
                ('userProfile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
