# Generated by Django 4.1.5 on 2023-07-07 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0027_remove_profile_follows'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='userProfile',
        ),
    ]
