# Generated by Django 4.1.5 on 2023-07-07 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0030_remove_user_following_remove_user_follows_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='userProfile',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
