# Generated by Django 4.1.5 on 2023-07-07 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0031_profile_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='user_following', to='network.profile'),
        ),
    ]
