# Generated by Django 4.1.5 on 2023-07-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0032_profile_follows'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='images/noPicture.png', upload_to='images/'),
        ),
    ]
