# Generated by Django 4.1.5 on 2023-07-07 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0034_remove_profile_profile_picture_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followed_by', to='network.profile'),
        ),
    ]
