# Generated by Django 4.1.5 on 2023-07-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0035_profile_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
