# Generated by Django 4.1.5 on 2023-08-09 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0036_alter_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='userProfile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
